# Generated by Django 4.2.5 on 2023-11-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('raza_paciente', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
