# Generated by Django 4.2.5 on 2023-11-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioApp', '0002_datos_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('apellido_propietario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('tipo_pelaje', models.CharField(max_length=50)),
            ],
        ),
    ]
