# Generated by Django 4.2.5 on 2023-11-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='memoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(default=500, max_length=100, verbose_name='Almacenamiento'),
            preserve_default=False,
        ),
    ]
