# Generated by Django 4.2.5 on 2023-11-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_producto_memoria_producto_almacenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_almacenamiento',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
