# Generated by Django 4.2.5 on 2023-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_producto_tipo_almacenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='refrigeracion_cpu',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_optica',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
