# Generated by Django 4.2.5 on 2023-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_producto_refrigeracion_cpu_producto_unidad_optica'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mouse',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='teclado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
