# Generated by Django 4.2.5 on 2023-12-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_producto_mouse_producto_teclado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_almacenamiento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
