# Generated by Django 4.2.5 on 2023-12-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_producto_unidad_almacenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sistema_operativo',
            field=models.CharField(max_length=20),
        ),
    ]
