# Generated by Django 4.2.5 on 2023-12-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_alter_producto_sistema_operativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('numero_tarjeta', models.CharField(max_length=100, verbose_name='Numero Tarjeta')),
                ('fecha_exp', models.DateField(verbose_name='Fecha expiracion')),
            ],
        ),
    ]
