# Generated by Django 4.2.5 on 2023-11-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ram', models.CharField(max_length=100, verbose_name='RAM')),
                ('procesador', models.CharField(max_length=100, verbose_name='Procesador')),
                ('grafica', models.CharField(max_length=100, verbose_name='Gráfica')),
                ('memoria', models.CharField(max_length=100, verbose_name='Memoria')),
                ('sistema_operativo', models.CharField(max_length=100, verbose_name='Sistema Operativo')),
                ('placa', models.CharField(max_length=100, verbose_name='Placa Madre')),
                ('gabinete', models.CharField(max_length=100, verbose_name='Gabinete')),
                ('fuente', models.CharField(max_length=100, verbose_name='Fuente de Poder')),
            ],
        ),
    ]
